### PR TITLE
Adds fortmatic support in instant

### PR DESCRIPTION
**Pull request by Agupane**
## Description

This pr adds support for fortmatic as a new provider, if the user does not have metamask installed, he will be able to connect using fortmatic.

## Looks like this now (Update 18/10/2019):

image
image

## Testing instructions

- Build the 0x instant app
- Open the 0x instant app and you will be able to connect using `metamask` or `fortmatic`, just log in with fortmatic and you are done.
- Set `INSTANT_FORTMATIC_API_KEY` with a valid fortmatic api key
- **Note**: I wasn't able to test this on kovan, I can't get available assets, it works ok on mainnet

## Types of changes

* New feature (non-breaking change which adds functionality)

## Checklist:

-   [x] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Update documentation as needed.
-   [ ] Add new entries to the relevant CHANGELOG.jsons.

### CODE REVIEW

**Comment by fragosti** [comment]
hey @Agupane, thanks for the PR! While we are excited about supporting Formatic, I don't think this implementation would pass design review. It was my understanding that you guys had synched up about the design. Here is the Figma file for reference:
https://www.figma.com/file/HCuoen1UlZ4HFARQWMonKu5S/0x-Instant?node-id=284%3A96

**Comment by fvictorio** [comment]
Sounds good @fragosti, thanks. While we work on the UI part, would you mind taking a quick look at the approach, to see if it makes sense to you?

**Comment by Agupane** [comment]
Hi @fragosti, I'd updated the designs, please take a look

**Comment by fragosti** [comment]
Hi @Agupane. These screenshots aren't exactly like the design so I'm asking @chriskalani whether they make sense.

**Comment by chriskalani** [comment]
@Agupane we need this to look like the design we provided. Here is a link directly to the frame for you to reference: https://www.figma.com/file/HCuoen1UlZ4HFARQWMonKu5S/0x-Instant?node-id=2150%3A1631

Screen Shot 2019-10-17 at 2 49 02 PM

**Comment by Agupane** [comment]
Hi @chriskalani @fragosti, thanks for the feedback!, I'd made the modifications, it looks like this now:
image
image

**Comment by Jmjin** [comment]
Hey @fragosti checking in here, we are ready for a review, it'd great if you can have a look and leave comments where needed :)

**Comment by chriskalani** [comment]
Those arrows don't match the design. Also "Order Details" shouldn't show up until a wallet has been selected.

**Comment by Agupane** [comment]
Hi @chriskalani I'd updated the styling, it looks like this now:
image
image

**Comment by Jmjin** [comment]
This PR has been ready for review for quite a while, can we get a review on this?

**Comment by dave4506** [comment]
Closing the PR because I have rebased the PR off of post-v3 development branch. Refer to PR #2404 for the latest changes and the eventually addition of Fortmatic to 0x instant. Big thanks to @Agupane @Jmjin and the Fortmatic team for putting the time in on this PR!

We will be testing and making changes to the work and testing it internally.

**Pull request closed without merging**
