### PR TITLE
[website] Translates landing page into Japanese [WIP]

### PR DESCRIPTION
**Pull request by hryk**
## Description

This PR adds Japanese translation of landing page.

## Testing instructions

Manual testing.

## Checklist:

*   [ ] Prefix PR title with `[WIP]` if necessary.
*   [x] Prefix PR title with bracketed package name(s) corresponding to the changed package(s). For example: `[sol-cov] Fixed bug`.
*   [ ] Add tests to cover changes as needed.
*   [ ] Update documentation as needed.
*   [ ] Add new entries to the relevant CHANGELOG.jsons.

### CODE REVIEW

**Comment by hryk** [comment]
Is there any action should I take to request review for this PR?

**Comment by fabioberger** [comment]
It's tough for us to review given our lack of Japanese speakers. @hryk was this translated using Google translate?

**Comment by hryk** [comment]
No, I translated by myself because google translate sometimes generate wired Japanese. I'm a Japanese speaker.

> It's tough for us to review given our lack of Japanese speakers.

Indeed, It is difficult to prove this translation have good quality ...

**Comment by BMillman19** [comment]
@hryk ill take a look today!

**Comment by BMillman19** [comment]
Let me sync with Blake to see if we can get someone to proofread this

**Comment by BMillman19** [comment]
@hryk thanks for your translation, we'll look to getting it reviewed and ready for merge by this week =)

**Comment by hryk** [comment]
@BMillman19 Thanks! I'm looking forward to see 
the website with my language.

**Comment by LogvinovLeon** [comment]
@BMillman19 This week was 3 month ago ;)

**Comment by hryk** [comment]
@LogvinovLeon @BMillman19 I will translate current website and then recreate PR :D

**Pull request closed without merging**
