### PR TITLE
Order Watcher validate order on addOrder

### PR DESCRIPTION
**Pull request by dekz**
## Description

Allow a user to specify whether they would like to receive an order state update when the order is added to order state watcher

## Motivation and Context

When pulling orders from SRA it's beneficial to get the order state before adding to the internal order book. 

It's a bit of wasted effort to do this outside of the order watcher through order state utils as you could have to create a couple of lazy stores out of band.

## Types of changes

*   [ ] Bug fix (non-breaking change which fixes an issue)
*   [x] New feature (non-breaking change which adds functionality)
*   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

*   [ ] Change requires a change to the documentation.
*   [x] Added tests to cover my changes.
*   [x] Added new entries to the relevant CHANGELOG.jsons.
*   [ ] Labeled this PR with the 'WIP' label if it is a work in progress.
*   [ ] Labeled this PR with the labels corresponding to the changed package.

### CODE REVIEW

**Comment by fabioberger** [comment]
@LogvinovLeon this is the same config that Avonian wanted... Should we re-consider it?

**Comment by dekz** [comment]
I've also made some changes to perform the balance and allowance requests asynchronously. I've noticed that these can take a noticeable amount of time when it hits a cold cache. 

After experimenting, I think the added benefit of this (rather than requesting the state directly through `exchange.getOrderState` is that it also primes the cache for future updates. Rather than hitting a cold cache as soon as a partial fill happens.

**Comment by fabioberger** [comment]
I think we should make these changes @dekz. Is it possible to wait with merging? I already started refactoring OrderWatcher out of 0x.js. Maybe we could re-base these changes once that gets merged?

**Comment by dekz** [comment]
Yeah there's no rush at all

**Comment by dekz** [comment]
Going to re-open this after v2.

**Pull request closed without merging**
