### PR TITLE
[asset-buyer][instant] downgrade lodash to be consistent with the rest of 0x packages

### PR DESCRIPTION
**Pull request by BMillman19**
## Description

* Reduces bundle size

## Checklist:

*   [ ] Prefix PR title with `[WIP]` if necessary.
*   [ ] Prefix PR title with bracketed package name(s) corresponding to the changed package(s). For example: `[sol-cov] Fixed bug`.
*   [ ] Add tests to cover changes as needed.
*   [ ] Update documentation as needed.
*   [ ] Add new entries to the relevant CHANGELOG.jsons.

### CODE REVIEW

**Comment by fragosti** [comment]
No yarn.lock change?

**Comment by BMillman19** [comment]
@fragosti hmm apparently not

**Comment by fragosti** [comment]
@BMillman19 did you change it manually or did you do `yarn remove lodash && yarn add lodash@myversion` ?

**Comment by fragosti** [comment]
I guess you saw the decrease in bundle size so it worked? I would expect a change to yarn.lock tho :P

**Comment by steveklebanoff** [comment]
It looks like `sol-doc` uses `^4.17.10`, so that may explain the lack of change in `yarn.lock`: https://github.com/0xProject/0x-monorepo/blob/development/packages/sol-doc/package.json#L33

**Pull request merged**
