### PR TITLE
Fixed the relative resolver not checking if the file can be read in the

### PR DESCRIPTION
**Pull request by ritave**

### CODE REVIEW

**Comment by fabioberger** [comment]
Thanks for the fix  @ritave! Can you please add an entry in the `CHANGELOG.json` for `sol-resolver` explaining the bug fix? 

Once this is added, I'll merge.

**Comment by ritave** [comment]
@fabioberger ping

**Comment by LogvinovLeon** [comment]
Not `CHANGELOG.md` but `CHANGELOG.json`. `CHANGELOG.md` is auto-generated

**Comment by LogvinovLeon** [comment]
You can also allow us to modify that PR and we can fix it

**Comment by fabioberger** [comment]
Can you fix and merge @LogvinovLeon?

**Comment by LogvinovLeon** [comment]
No. I need the author (@ritave ) to give me permissions https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by LogvinovLeon** [comment]
Ok, I'll first merge if and then fix

**Pull request merged**
