### PR TITLE
[WIP] Update TypeScript to version ^2.8.0

### PR DESCRIPTION
**Pull request by albrow**
## Description

This PR changes the TypeScript version we use in the monorepo from 2.7 to 2.8. This upgrade was somewhat forced upon us because of a change made in a dependency. (The type definitions for react and prop-types in some part of the dependency tree are not compatible with version 2.7).

I discovered this by running __packages/monorepo-scripts/src/test_installation.ts__. It will fail on TypeScript version 2.7 but succeed if we use version 2.8.

## Testing instructions

Start verdaccio. Run `yarn run:publish:local` and then `yarn test:installation:local`.

## Types of changes

* Bug fix (non-breaking change which fixes an issue)

## Checklist:

*   [ ] Prefixed the title of this PR with `[WIP]` if it is a work in progress.
*   [ ] Prefixed the title of this PR with bracketed package name(s) corresponding to the changed package(s). For example: `[sol-cov] Fixed bug`.
*   [ ] Added tests to cover my changes, or decided that tests would be too impractical.
*   [ ] Updated documentation, or decided that no doc change is needed.
*   [ ] Added new entries to the relevant CHANGELOG.jsons.

### CODE REVIEW

**Comment by albrow** [comment]
Looks like TSLint requires us to include typescript as a dependency for each package. I guess I'll update this PR to do this.

**Comment by fabioberger** [comment]
Is this ready for a review @albrow? Saw your comment above but looks like you haven't added back in the Typescript dep.

**Comment by ritave** [comment]
Just stumbled upon this PR - keep in mind that Typescript 2.9 has breaking changes concerning JSON importing and is a bit bigger change, might consider moving straight to 2.9?

**Comment by albrow** [comment]
@fabioberger sorry I got pulled away for something else last night. Marked this PR as WIP and will finish it now.

**Comment by albrow** [comment]
Superseded by https://github.com/0xProject/0x-monorepo/pull/945. I didn't realize that version `^2.8.0` gets resolved to `2.9.2`. So #945 specifies exactly version `2.9.2` and updates the branch name and PR description for clarity.

**Pull request closed without merging**
