### PR TITLE
Website market making website svg consistency issues

### PR DESCRIPTION
**Pull request by dave4506**
## Types of changes

* Bug fix (non-breaking change which fixes an issue)

For future reference purposes going to highlight the issue with the svgs here: 

Svgs created at different sizes in a design software will not have the right stroke width when the svg assets are "compressed" to fit a specific pixel dimension

Svg files as designed in a design software:
screen shot 2019-01-24 at 8 00 25 pm

Larger svg file compressed to the same size as the smaller svg:
screen shot 2019-01-24 at 8 00 39 pm

Larger svg file compressed to the same size as the smaller svg but with same stroke width

screen shot 2019-01-24 at 8 05 59 pm

The semi transparent effect of the `low-cost.svg` is due to an issue with the svg mask property.
It appears to be an issue though with how Figma exports the svg asset: 

Before
``
<mask id="mask0" mask-type="alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="80" height="80">
<path d="M40 78.9333C61.5023 78.9333 78.9333 61.5023 78.9333 40C78.9333 18.4977 61.5023 1.06665 40 1.06665C18.4977 1.06665 1.06665 18.4977 1.06665 40C1.06665 61.5023 18.4977 78.9333 40 78.9333Z" fill="#00AE99" stroke="#00AE99" stroke-width="2" stroke-miterlimit="10"/>
</mask>
``

After

``
<mask id="mask0" mask-type="alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="80" height="80">
<path d="M40 78.9333C61.5023 78.9333 78.9333 61.5023 78.9333 40C78.9333 18.4977 61.5023 1.06665 40 1.06665C18.4977 1.06665 1.06665 18.4977 1.06665 40C1.06665 61.5023 18.4977 78.9333 40 78.9333Z" fill="#FFFFFF" stroke="#FFFFFF" stroke-width="2" stroke-miterlimit="10"/>
</mask>
``

I had to change the fill and stroke colors to white in the path and it appears to solve the issue. 

## Checklist:

-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Update documentation as needed.
-   [ ] Add new entries to the relevant CHANGELOG.jsons.

### CODE REVIEW

**Comment by fragosti** [comment]
you've been working with @chriskalani on this right? If says it's all good, it's all good from me.

**Comment by chriskalani** [comment]
I supplied updated SVGs but I haven't reviewed it on the site yet. Is there a dogfood link?

**Comment by dave4506** [comment]
Heres the screenshots:

Before: 

screen shot 2019-01-31 at 3 36 56 pm

After:

screen shot 2019-01-31 at 3 35 18 pm

**Comment by chriskalani** [comment]
👍

**Pull request merged**
