### PR TITLE
[sol-cov] add support for CREATE opcodes

### LINKED ISSUE #703: [sol-cov] coverage report is incorrect
## Current Behavior

I haven't investigated too closely, however when I run code coverage, the generated report is incorrect.

As you can see in the img below, line 111 has been covered, but 110 has not. In reality, lines 110 - 115 should all be covered

screen shot 2018-06-14 at 1 46 52 pm

## Steps to Reproduce (for bugs)

The above report was generated using the current sol-cov v2-prototype branch with PR #702 [commit here](https://github.com/perissology/0x-monorepo/tree/7a41a5249fcb8457cb8beb823ce9a1362cdbfa98)

you can find instructions to reproduce [here](https://github.com/Giveth/giveth-bridge/issues/4#issuecomment-397425028)

### PR DESCRIPTION
**Pull request by perissology**
## Description

This PR adds support for covering the case when a contract is deployed from a contract. Fixes #703.

## Testing instructions

see #703

## Types of changes

*   [ ] Bug fix (non-breaking change which fixes an issue)
*   [x] New feature (non-breaking change which adds functionality)
*   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

*   [ ] Change requires a change to the documentation.
*   [ ] Added tests to cover my changes.
*   [ ] Added new entries to the relevant CHANGELOG.jsons.
*   [ ] Labeled this PR with the 'WIP' label if it is a work in progress.
*   [ ] Labeled this PR with the labels corresponding to the changed package.

### CODE REVIEW

**Comment by perissology** [comment]
okay, got it working.

I'm not really a fan of setting the `TraceInfoNewContract.bytecode` to the `runtimeBytecode` of the created contract, but it was the least amount of changes to get this to work and I didn't want to start refactoring too much w/o input from you'll.

**Comment by perissology** [comment]
any updates on getting this merged?

**Comment by fabioberger** [comment]
@LogvinovLeon can you take another look at this?

**Comment by perissology** [comment]
Are CREATE opcodes supported yet? If not, any plans to take a look at this?

**Comment by LogvinovLeon** [comment]
Hi @perissology. Create opcodes are not supported yet. I have plans to look into that, but unfortunately not this week.

**Pull request closed without merging**
