### PR TITLE
Prevent multiple connections in 0x Connect websocket

### PR DESCRIPTION
**Pull request by dekz**
## Description

Prevents multiple connections from being created (and their respective connection handlers)

## Motivation and Context

In practice, calling a large number of subscribes asynchronously can cause connect to open multiple websocket connections as there is no locking mechanism. Rather than introduce a lock and queue we can introduce internal state and an interval.

## Types of changes

*   [ ] Bug fix (non-breaking change which fixes an issue)
*   [ ] New feature (non-breaking change which adds functionality)
*   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

*   [ ] Change requires a change to the documentation.
*   [ ] Added tests to cover my changes.
*   [ ] Added new entries to the relevant CHANGELOG.jsons.
*   [ ] Labeled this PR with the 'WIP' label if it is a work in progress.
*   [ ] Labeled this PR with the labels corresponding to the changed package.

### CODE REVIEW

**Comment by fabioberger** [comment]
As per our offline conversation, let's instead use a lock around the connection creation logic so that subsequent attempts at establishing a connection will await the completion of previous calls.

**Comment by dekz** [comment]
In this latest commit I changed it to use internal state to prevent multiple connections/multiple handlers being registered by tracking some internal state. 

@BMillman19 I know you're working on some websocket stuff currently, how do you feel about this approach versus introducing a locking mechanism. I think a locking mechanism would force async down to the caller to await on subscribes. This feels like it breaks event emitter conventions/interfaces a bit. Thoughts?

**Comment by BMillman19** [comment]
@dekz I was thinking about this recently, in order to simplify this, we could have the subscribe method be only called once with an array of subscriptionOpts

**Comment by dekz** [comment]
I think that could help, we would still need an additional `subscribe` or `add` for long running processes that sync tokenPairs and want to add new ones without a restart. Perhaps a second call to subscribe with more options would allow that but it kind of can put us in a similar situations. Hmmmm

**Comment by BMillman19** [comment]
@dekz lemme know if you want to hop on a call and we can talk thru it

**Pull request closed without merging**
